#spring:
# application:
#  name: ai-service
# config:
#  import: optional:configserver:http://localhost:8888
#
#eureka:
# client:
#  service-url:
#   defaultZone: http://localhost:8761/eureka/
# instance:
#  hostname: localhost
#  prefer-ip-address: true
#
#server:
# port: 8083

# spring:
#  application:
#   name: ai-service
#  config:
#   import: optional:configserver:http://localhost:8888



spring:
  application:
    name: ai-service

  cloud:
    config:
      enabled: false   # ❌ Render pe Config Server nahi

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

server:
  port: 8080

# ❌ Eureka completely OFF
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# ❌ Kafka OFF (Render does not support Kafka)
kafka:
  enabled: false
  topic:
    name: activity-events

# ✅ Gemini AI Config
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

management:
  endpoints:
    web:
      exposure:
        include: mappings,health


