#14-01-2026
# spring:
#   application:
#     name: api-gateway
#   config:
#     import: optional:configserver:http://localhost:8888

# server:
#   port: 8080
#--------------------------------------------------------------

#spring:
#  application:
#    name: api-gateway
#  config:
#    import: optional:configserver:http://localhost:8888
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#


spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

# ðŸ”´ IMPORTANT: Disable Eureka completely for Render
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

