

# spring:
#   application:
#     name: activity-service
#   config:
#     import: optional:configserver:http://localhost:8888

spring:
  application:
    name: activity-service

  cloud:
    config:
      enabled: false   # ðŸ”´ IMPORTANT for Render

server:
  port: 8080

eureka:
  client:
    enabled: false

    
